
import { GastoItem, UnidadItem } from './types';

export const CLASIFICADOR_GASTO: GastoItem[] = [
  { partida: "10000", nombre: "Servicios Personales" },
  { partida: "11000", nombre: "Remuneraciones al Personal de Carácter Permanente" },
  { partida: "11100", nombre: "Dietas" },
  { partida: "11101", nombre: "Dietas de Legisladores Estatales" },
  { partida: "11200", nombre: "Haberes" },
  { partida: "11201", nombre: "Haberes" },
  { partida: "11300", nombre: "Sueldos base al personal permanente" },
  { partida: "11301", nombre: "Sueldos base al personal de confianza" },
  { partida: "11302", nombre: "Sueldos al personal de base" },
  { partida: "11303", nombre: "Vida cara" },
  { partida: "11400", nombre: "Remuneraciones por adscripción laboral en el extranjero" },
  { partida: "11401", nombre: "Remuneraciones por adscripción laboral en el extranjero" },
  { partida: "12000", nombre: "Remuneraciones al Personal de Carácter Transitorio" },
  { partida: "12100", nombre: "Honorarios asimilables a salarios" },
  { partida: "12101", nombre: "Honorarios asimilables a salarios" },
  { partida: "12200", nombre: "Sueldos base al personal eventual" },
  { partida: "12201", nombre: "Sueldo base al personal eventual" },
  { partida: "12300", nombre: "Retribuciones por servicios de carácter social" },
  { partida: "12301", nombre: "Retribuciones por servicios de carácter social" },
  { partida: "12400", nombre: "Retribución a los representantes de los trabajadores" },
  { partida: "12401", nombre: "Retribuciones a los representantes de los trabajadores" },
  { partida: "13000", nombre: "Sueldos Base al Personal Permanente" },
  { partida: "13100", nombre: "Primas por años de servicios efectivos prestados" },
  { partida: "13101", nombre: "Prima quinquenal" },
  { partida: "13102", nombre: "Prima de antigüedad" },
  { partida: "13103", nombre: "Estímulo por años de servicio" },
  { partida: "13200", nombre: "Primas de vacaciones, dominical y gratificación de fin de año" },
  { partida: "13201", nombre: "Prestaciones de fin de año en efectivo" },
  { partida: "13202", nombre: "Prima vacacional" },
  { partida: "13203", nombre: "Prima dominical" },
  { partida: "13204", nombre: "Prestaciones de fin de año en especie" },
  { partida: "13205", nombre: "Canasta navideña" },
  { partida: "13300", nombre: "Horas extraordinarias" },
  { partida: "13301", nombre: "Horas extraordinarias" },
  { partida: "13400", nombre: "Compensaciones" },
  { partida: "13401", nombre: "Compensación por servicios al personal de base" },
  { partida: "13402", nombre: "Compensación por servicios al personal de confianza" },
  { partida: "13403", nombre: "Compensación por servicios eventuales" },
  { partida: "13404", nombre: "Compensación por trabajos especiales" },
  { partida: "13405", nombre: "Compensación garantizada" },
  { partida: "14101", nombre: "Aportaciones al ISSSTE" },
  { partida: "14102", nombre: "Aportaciones al IMSS" },
  { partida: "21101", nombre: "Consumibles de oficina" },
  { partida: "21102", nombre: "Útiles, artículos, equipos y herramientas menores de oficina" },
  { partida: "21103", nombre: "Papelería" },
  { partida: "26101", nombre: "Combustible" },
  { partida: "31101", nombre: "Energía eléctrica" },
  { partida: "37501", nombre: "Viáticos en el país" },
  { partida: "44101", nombre: "Ayudas sociales a personas" },
  { partida: "51501", nombre: "Equipo de cómputo y de tecnología de la información" }
  // ... (truncado por brevedad en este ejemplo, pero incluiría todo lo relevante del CSV)
].concat([
    { partida: "20000", nombre: "Materiales y Suministros" },
    { partida: "21100", nombre: "Materiales, útiles y equipos menores de oficina" },
    { partida: "21200", nombre: "Materiales y útiles de impresión y reproducción" },
    { partida: "21401", nombre: "Material de limpieza y mantenimiento e insumos para equipos IT" },
    { partida: "22101", nombre: "Alimentos para el personal institucional" },
    { partida: "26105", nombre: "Combustible para Viatico" },
    { partida: "33401", nombre: "Servicios de capacitación" },
    { partida: "35501", nombre: "Reparación y mantenimiento de equipo de transporte" },
    { partida: "38201", nombre: "Gastos de orden social y cultural" },
    { partida: "38202", nombre: "Gastos de Feria y Festividades" }
]);

export const UNIDADES_ADMINISTRATIVAS: UnidadItem[] = [
  { codigo: "A0100", nombre: "SINDICO REGIDORES", tipo: "Acumulativa" },
  { codigo: "A0101", nombre: "SINDICO REGIDORES", tipo: "Registro" },
  { codigo: "B0100", nombre: "PRESIDENCIA MUNICIPAL", tipo: "Acumulativa" },
  { codigo: "B0101", nombre: "PRESIDENCIA MUNICIPAL", tipo: "Registro" },
  { codigo: "B0102", nombre: "COORD. DE ASESORES", tipo: "Registro" },
  { codigo: "C0100", nombre: "SECRETARIA PARTICULAR", tipo: "Acumulativa" },
  { codigo: "C0101", nombre: "SECRETARIA PARTICULAR", tipo: "Registro" },
  { codigo: "C0200", nombre: "DIRECCIÓN DE COMUNICACIÓN SOCIAL", tipo: "Acumulativa" },
  { codigo: "C0201", nombre: "DIRECCIÓN DE COMUNICACIÓN SOCIAL", tipo: "Registro" },
  { codigo: "D0100", nombre: "SECRETARIA GENERAL", tipo: "Acumulativa" },
  { codigo: "D0101", nombre: "SECRETARIA GENERAL", tipo: "Registro" },
  { codigo: "D0200", nombre: "DIRECCION JURIDICA", tipo: "Acumulativa" },
  { codigo: "D0201", nombre: "DIRECCION JURIDICA", tipo: "Registro" },
  { codigo: "E0100", nombre: "TESORERIA MUNICIPAL", tipo: "Acumulativa" },
  { codigo: "E0101", nombre: "DESPACHO DE LA TESORERIA", tipo: "Registro" },
  { codigo: "F0100", nombre: "ORGANO INTERNO DE CONTROL", tipo: "Acumulativa" },
  { codigo: "G0100", nombre: "DIRECCION GENERAL DE SEGURIDAD CIUDADANA", tipo: "Acumulativa" },
  { codigo: "H0100", nombre: "OFICIALIA MAYOR", tipo: "Acumulativa" },
  { codigo: "I0100", nombre: "DIRECCION GENERAL DE OBRA PUBLICA", tipo: "Acumulativa" },
  { codigo: "J0100", nombre: "DIRECCION DE DESARROLLO RURAL", tipo: "Acumulativa" },
  { codigo: "K0100", nombre: "DIRECCION DE DESARROLLO SOCIAL", tipo: "Acumulativa" },
  { codigo: "L0100", nombre: "DIRECCION DE TURISMO", tipo: "Acumulativa" },
  { codigo: "N0100", nombre: "DIRECCION DE EDUCACION Y CULTURA", tipo: "Acumulativa" },
  { codigo: "P0100", nombre: "DIRECCION DE SERVICIOS PUBLICOS MUNICIPALES", tipo: "Acumulativa" },
  { codigo: "Q0101", nombre: "DIRECCION DE PLANEACION", tipo: "Registro" }
];
